### PR TITLE
Reorganize to not be a grammar at the top-level

### PR DESCRIPTION
**Pull request by krame505**
This is pretty much what we discussed.  Grammars moved to a seperate sub-folder, reorganized test and example grammars/directories.  Scripts are replaced with Makefiles.  

I'm not sure how to check if the Jenkinsfile works - could someone take a look at this?  

Note to self: Rename this repo to `ableC-skeleton` after merging this PR.

### CODE REVIEW

**Comment by ericvanwyk** [comment]
This looks good to me.

**Comment by ericvanwyk** [comment]
Actually, why are Makefile vars used in the Makefile in the modular analysis directory?  This seems more complicated than it needs to be.

**Comment by ericvanwyk** [comment]
Same comment on Makefile in examples.  This may work but seems too complex.  Let's chat sometime.

**Comment by krame505** [comment]
That is for generating the includes for other extensions - same thing as what Ted had in his example bash script.  Not sure how to make it less complex?

**Comment by ericvanwyk** [comment]
That capability isn't needed here.  You only want to run the modular
analyses on the extension and the host - it shouldn't include other
extensions.

**Comment by tedinski** [comment]
IIRC, the problem is extensions that depend on other extensions? That bit looks okay to me, fwiw...

**Comment by ericvanwyk** [comment]
If an extension depends on others, then why not list them explicitly?
Doing so states the dependencies in a way the one can see and understand.

If an extension doesn't depend on others, why include all of this?

I'm just not a fan of too much Makefile trickery that doesn't actually do
something.

Are we thinking this is the right place to demonstrate how this could be
done?

**Comment by krame505** [comment]
Including extra directories in the Silver search path isn't problematic.
And I am opposed to making the user list all the extensions used as
dependencies in 3 or 4 places when setting up their project (example, test,
and modular_analyses Makefiles) when a simple wildcard will do just fine.
If the extension writer can just copy the whole skeleton repo without
needing to update things in a bunch of specific spots, that is better.

Lucas Kramer

**Comment by krame505** [comment]
Also, I don't see not having an explicit list of dependencies in these
locations as a problem - this should be well documented in the extension
README file, there is no reason a user would want to look for this in the
modular_analyses or tests directories.

Lucas Kramer

**Comment by ericvanwyk** [comment]
The issues here all depend on what our intentions are with this.  If it is
just to be something that experienced people copy and modify when starting
an extension, then all the Makefile trickery with wildcards is fine.

If we are writing something that is more tutorial in nature, then being
explicit about things is better.

It is fine to leave it as it is now if this is not meant to be much of a
tutorial for new ext writers.

**Comment by krame505** [comment]
After a talk with Eric, he said that he is fine if this isn't going to be primarily a tutorial extension.  I will add a comment to the Makefiles describing what is going on.

**Comment by krame505** [comment]
Since Ted and Eric both signed off on this earlier, I am going to go ahead and merge.

**Pull request merged**
